[versions]
processLifecycle = "2.3.1"
fcm = "21.0.1"

[libraries]
fcm = { module = "com.google.firebase:firebase-messaging", version.ref = "fcm" }
processLifecycle = { module = "androidx.lifecycle:lifecycle-process", version.ref = "processLifecycle" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version = "1.5.0" }